### PR TITLE
PLAT-42: Rework the login page

### PR DESCRIPTION
**Pull request by dondrzzy**
## JIRA TICKET NAME
[PLAT-42: Rework the login page](https://issues.openmrs.org/browse/PLAT-42)

## Description of what I changed

- Center the login page
- Add some UI/UX value
- Make the `forgot username/password?` a link.

## Issue I worked on
[PLAT-42](https://issues.openmrs.org/browse/PLAT-42)

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Review by emasys — APPROVED** [review]
LGTM

**Review by IAMOTZ — APPROVED** [review]
Looks Good To Me

**Comment by IAMOTZ** [comment]
From the ticket description for this Pull Request, one of the issues that this pull request is supposed to fix is: _`...has a welcome message that is incomplete...`_ .

But I am not seeing any of your changes addressing the welcome message, how about it @dondrzzy ?

**Comment by dkayiwa** [comment]
@dondrzzy did you see the review comments on this pull request?

**Comment by dondrzzy** [comment]
@IAMOTZ, I removed the welcome message. A user is still anonymous before they log in so better yet, welcome them when they have logged in. Then you are sure if its an admin or a normal user or the others.

**Review by alexmochu — APPROVED** [review]
LGTM

**Comment by IAMOTZ** [comment]
Hey @dondrzzy 
From my UI/UX sense, looking at this page from a user perspective:
screen shot 2018-08-17 at 12 07 42 pm
There is nothing informing me that I am on a `Platform UI` Login Page, if not for the Logo, I won't be even sure if this page has anything to do with OpenMRS. What do you think @dondrzzy?

**Comment by dondrzzy** [comment]
@IAMOTZ, I think you have a point. Let me address that.

**Comment by dondrzzy** [comment]
Hey @IAMOTZ, I have added a header to inform a user that they are on the OpenMRS platform. I have also attached a new image on the ticket.

**Comment by IAMOTZ** [comment]
Nice one @dondrzzy.
I believe this Pull Request is ready to go in.

**Comment by dondrzzy** [comment]
Thank you @IAMOTZ  for your attention to detail.

**Pull request merged**
