### PR TITLE
PLAT-44: Add enzyme adapter configurations to setupTests file

### PR DESCRIPTION
**Pull request by dondrzzy**
## JIRA TICKET NAME
[PLAT-44: Add enzyme adapter configurations to setupTests file](https://issues.openmrs.org/browse/PLAT-44)

## Description of what I changed

- Add enzyme adapter configurations to setupTests.js file
- Add setupTestFrameworkScriptFile to the jest configuration

## Issue I worked on
[PLAT-44](https://issues.openmrs.org/browse/PLAT-44)

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Review by dotNesh — APPROVED** [review]
LGTM

**Review by alexmochu — COMMENTED** [review]
LGTM

**Review by alexmochu — APPROVED** [review]

**Comment by dkayiwa** [comment]
Can you look into these merge conflicts?

**Review by emmabaye — APPROVED** [review]
LGTM

**Comment by dondrzzy** [comment]
@dkayiwa, merge conflicts are resolved.

**Pull request merged**
